---
deployment:
  tasks:
    - export DEPLOYPATH=/home/temisodi/public_html/
    - /bin/cp -f index.html $DEPLOYPATH
    - /bin/cp -f styles.css $DEPLOYPATH
    - /bin/cp -f scripts.js $DEPLOYPATH
    - /bin/cp -rf images $DEPLOYPATH
